name: Deploy to Neocities

# Only deploy when pushing to main
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false # Set to true to delete orphaned files on Neocities
        dist_dir: .
